# Generated by Django 6.1 on 2026-09-01 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringChore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('interval_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('next_due_date', models.DateField()),
                ('last_done_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
